# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: gh-pages-main
    env:
      JW_SITE_NAME: ${{ secrets.JW_SITE_NAME }}
      JW_CLOUD_NAME: ${{ secrets.JW_CLOUD_NAME }}
      JW_CLOUD_APP_KEY: ${{ secrets.JW_CLOUD_APP_KEY }}
      JW_CLOUD_CLIENT_KEY: ${{ secrets.JW_CLOUD_CLIENT_KEY }}
      JW_CLOUD_APPLICATION_ID: ${{ secrets.JW_CLOUD_APPLICATION_ID }}

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true # Download LFS files.
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
